[package]

name = "valico"
version = "2.1.0"
authors = ["Stanislav Panferov <fnight.m@gmail.com>"]
description = "JSON Schema validator and JSON coercer"
keywords = ["json", "validator", "json-schema"]
license = "MIT"
documentation = "http://rustless.org/valico/doc/valico/"
homepage = "https://github.com/rustless/valico"
build = "build.rs"

[dependencies]
regex = "0.1"
lazy_static = "0.2"
url = "1"
jsonway = "2.0"
uuid = {version = "0.6", features = ["v4"]}
phf = "0.7"
typeable = "0.1"
traitobject = "0.0"
serde = "1.0"
serde_json = "1.0"

[build-dependencies.phf_codegen]
version = "0.7"

[[test]]
name = "tests"
